language: python

# run on Travis 'new' container-based infrastructure
sudo: false

# no need of git history
git:
  depth: 1

# test only the master branch
branches:
  only:
    - master

cache:
  directories:
    - $HOME/miniconda

before_cache:
  - rm -rf $HOME/miniconda/locks
  - rm -rf $HOME/miniconda/pkgs
  - rm -rf $HOME/miniconda/var
  - rm -rf $HOME/miniconda/conda-meta/history

before_install:
  - if test -e $HOME/miniconda/bin; then
      echo "miniconda already installed.";
    else
       wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
       bash miniconda.sh -b -u -p $HOME/miniconda;
       hash -r;
    fi;
    export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda env update --name shennong -f environment.yml
  - source activate shennong
  - make install
  - pip install codecov

script:
  - python setup.py test

after_success:
  - codecov
