name: shennong
channels:
  - coml
dependencies:
  - python>=3.6
  - cython
  - flake8
  - h5features>=1.3.2
  - h5py
  - ipython
  - joblib
  - numpy
  - pip
  - pykaldi
  - pyparsing
  - pytest
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scipy
  - sox  # sox binary
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - json-tricks
      - ninja
