name: shennong
channels:
  - pykaldi
dependencies:
  - python=3.7
  - cython
  - flake8
  - h5py
  - ipython
  - joblib
  - numpy
  - pykaldi
  - pyparsing
  - pytest
  - pytest-cov
  - pytest-runner
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - ninja
      - json-tricks
      - git+https://github.com/bootphon/h5features.git
