name: shennong
channels:
  - coml
dependencies:
  - python>=3.6
  - shennong-pykaldi
  - cython
  - flake8
  - h5features>=1.3.2
  - h5py
  - ipython
  - joblib
  # pykaldi is compiled on numpy-1.15, so the whole shennong must stay on the
  # 1.15 version
  - numpy==1.15.*
  - pip
  - pyparsing
  - pytest>=5.0
  - pytest-cov
  - pytest-runner
  - pyyaml
  - scipy
  - sox
  - sphinx
  - sphinx_rtd_theme
  - pip:
      - json-tricks==3.15.*
      - ninja
